use crate::options::Options;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Action {
    Accept,
    Abort,
    Cancel,
    ClearScreen,
    ClearQuery,
    ClearSelection,
    CursorDown,
    CursorUp,
    CursorLeft,
    CursorRight,
    CursorEnd,
    CursorHome,
    DeleteChar,
    DeleteWord,
    DeleteLine,
    PageDown,
    PageUp,
    ToggleDown,
    ToggleUp,
    ToggleAll,
    ToggleIn,
    ToggleOut,
    TogglePreview,
    TogglePreviewWrap,
    ToggleSort,
    PreviewUp,
    PreviewDown,
    PreviewPageUp,
    PreviewPageDown,
    BeginningOfLine,
    EndOfLine,
    SelectAll,
    DeselectAll,
    KillLine,
    Yank,
    UnixLineDiscard,
    UnixWordRubout,
    ForwardWord,
    BackwardWord,
    ForwardChar,
    BackwardChar,
    Reload,
    ReplaceQuery,
    Execute,
    ExecuteSilent,
    Ignore,
}

impl Action {
    pub fn from_string(s: &str) -> Option<Self> {
        match s {
            "accept" => Some(Self::Accept),
            "abort" => Some(Self::Abort),
            "cancel" => Some(Self::Cancel),
            "clear-screen" => Some(Self::ClearScreen),
            "clear-query" => Some(Self::ClearQuery),
            "clear-selection" => Some(Self::ClearSelection),
            "down" | "cursor-down" => Some(Self::CursorDown),
            "up" | "cursor-up" => Some(Self::CursorUp),
            "left" | "cursor-left" => Some(Self::CursorLeft),
            "right" | "cursor-right" => Some(Self::CursorRight),
            "end-of-line" => Some(Self::EndOfLine),
            "beginning-of-line" => Some(Self::BeginningOfLine),
            "delete-char" => Some(Self::DeleteChar),
            "delete-word" => Some(Self::DeleteWord),
            "delete-line" => Some(Self::DeleteLine),
            "page-down" => Some(Self::PageDown),
            "page-up" => Some(Self::PageUp),
            "toggle-down" => Some(Self::ToggleDown),
            "toggle-up" => Some(Self::ToggleUp),
            "toggle-all" => Some(Self::ToggleAll),
            "toggle-in" => Some(Self::ToggleIn),
            "toggle-out" => Some(Self::ToggleOut),
            "toggle-preview" => Some(Self::TogglePreview),
            "toggle-preview-wrap" => Some(Self::TogglePreviewWrap),
            "toggle-sort" => Some(Self::ToggleSort),
            "preview-up" => Some(Self::PreviewUp),
            "preview-down" => Some(Self::PreviewDown),
            "preview-page-up" => Some(Self::PreviewPageUp),
            "preview-page-down" => Some(Self::PreviewPageDown),
            "select-all" => Some(Self::SelectAll),
            "deselect-all" => Some(Self::DeselectAll),
            "kill-line" => Some(Self::KillLine),
            "yank" => Some(Self::Yank),
            "unix-line-discard" => Some(Self::UnixLineDiscard),
            "unix-word-rubout" => Some(Self::UnixWordRubout),
            "forward-word" => Some(Self::ForwardWord),
            "backward-word" => Some(Self::BackwardWord),
            "forward-char" => Some(Self::ForwardChar),
            "backward-char" => Some(Self::BackwardChar),
            "reload" => Some(Self::Reload),
            "replace-query" => Some(Self::ReplaceQuery),
            "execute" => Some(Self::Execute),
            "execute-silent" => Some(Self::ExecuteSilent),
            "ignore" => Some(Self::Ignore),
            _ => None,
        }
    }
}
